// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TodoServiceClient is the client API for TodoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TodoServiceClient interface {
	CreateNewNote(ctx context.Context, in *Note, opts ...grpc.CallOption) (*Response, error)
	GetNoteById(ctx context.Context, in *RequestId, opts ...grpc.CallOption) (*Response, error)
	GetAllNotes(ctx context.Context, in *RequestId, opts ...grpc.CallOption) (TodoService_GetAllNotesClient, error)
	ChangeNoteContent(ctx context.Context, in *Note, opts ...grpc.CallOption) (*Response, error)
	MarkDoneById(ctx context.Context, in *RequestId, opts ...grpc.CallOption) (*Response, error)
	DelNoteById(ctx context.Context, in *RequestId, opts ...grpc.CallOption) (*Response, error)
}

type todoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTodoServiceClient(cc grpc.ClientConnInterface) TodoServiceClient {
	return &todoServiceClient{cc}
}

func (c *todoServiceClient) CreateNewNote(ctx context.Context, in *Note, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/todo.TodoService/CreateNewNote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) GetNoteById(ctx context.Context, in *RequestId, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/todo.TodoService/GetNoteById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) GetAllNotes(ctx context.Context, in *RequestId, opts ...grpc.CallOption) (TodoService_GetAllNotesClient, error) {
	stream, err := c.cc.NewStream(ctx, &TodoService_ServiceDesc.Streams[0], "/todo.TodoService/GetAllNotes", opts...)
	if err != nil {
		return nil, err
	}
	x := &todoServiceGetAllNotesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TodoService_GetAllNotesClient interface {
	Recv() (*Note, error)
	grpc.ClientStream
}

type todoServiceGetAllNotesClient struct {
	grpc.ClientStream
}

func (x *todoServiceGetAllNotesClient) Recv() (*Note, error) {
	m := new(Note)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *todoServiceClient) ChangeNoteContent(ctx context.Context, in *Note, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/todo.TodoService/ChangeNoteContent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) MarkDoneById(ctx context.Context, in *RequestId, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/todo.TodoService/MarkDoneById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) DelNoteById(ctx context.Context, in *RequestId, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/todo.TodoService/DelNoteById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TodoServiceServer is the server API for TodoService service.
// All implementations must embed UnimplementedTodoServiceServer
// for forward compatibility
type TodoServiceServer interface {
	CreateNewNote(context.Context, *Note) (*Response, error)
	GetNoteById(context.Context, *RequestId) (*Response, error)
	GetAllNotes(*RequestId, TodoService_GetAllNotesServer) error
	ChangeNoteContent(context.Context, *Note) (*Response, error)
	MarkDoneById(context.Context, *RequestId) (*Response, error)
	DelNoteById(context.Context, *RequestId) (*Response, error)
	mustEmbedUnimplementedTodoServiceServer()
}

// UnimplementedTodoServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTodoServiceServer struct {
}

func (UnimplementedTodoServiceServer) CreateNewNote(context.Context, *Note) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNewNote not implemented")
}
func (UnimplementedTodoServiceServer) GetNoteById(context.Context, *RequestId) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNoteById not implemented")
}
func (UnimplementedTodoServiceServer) GetAllNotes(*RequestId, TodoService_GetAllNotesServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAllNotes not implemented")
}
func (UnimplementedTodoServiceServer) ChangeNoteContent(context.Context, *Note) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeNoteContent not implemented")
}
func (UnimplementedTodoServiceServer) MarkDoneById(context.Context, *RequestId) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkDoneById not implemented")
}
func (UnimplementedTodoServiceServer) DelNoteById(context.Context, *RequestId) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelNoteById not implemented")
}
func (UnimplementedTodoServiceServer) mustEmbedUnimplementedTodoServiceServer() {}

// UnsafeTodoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TodoServiceServer will
// result in compilation errors.
type UnsafeTodoServiceServer interface {
	mustEmbedUnimplementedTodoServiceServer()
}

func RegisterTodoServiceServer(s grpc.ServiceRegistrar, srv TodoServiceServer) {
	s.RegisterService(&TodoService_ServiceDesc, srv)
}

func _TodoService_CreateNewNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Note)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).CreateNewNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.TodoService/CreateNewNote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).CreateNewNote(ctx, req.(*Note))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_GetNoteById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).GetNoteById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.TodoService/GetNoteById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).GetNoteById(ctx, req.(*RequestId))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_GetAllNotes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RequestId)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TodoServiceServer).GetAllNotes(m, &todoServiceGetAllNotesServer{stream})
}

type TodoService_GetAllNotesServer interface {
	Send(*Note) error
	grpc.ServerStream
}

type todoServiceGetAllNotesServer struct {
	grpc.ServerStream
}

func (x *todoServiceGetAllNotesServer) Send(m *Note) error {
	return x.ServerStream.SendMsg(m)
}

func _TodoService_ChangeNoteContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Note)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).ChangeNoteContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.TodoService/ChangeNoteContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).ChangeNoteContent(ctx, req.(*Note))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_MarkDoneById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).MarkDoneById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.TodoService/MarkDoneById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).MarkDoneById(ctx, req.(*RequestId))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_DelNoteById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).DelNoteById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.TodoService/DelNoteById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).DelNoteById(ctx, req.(*RequestId))
	}
	return interceptor(ctx, in, info, handler)
}

// TodoService_ServiceDesc is the grpc.ServiceDesc for TodoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TodoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "todo.TodoService",
	HandlerType: (*TodoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNewNote",
			Handler:    _TodoService_CreateNewNote_Handler,
		},
		{
			MethodName: "GetNoteById",
			Handler:    _TodoService_GetNoteById_Handler,
		},
		{
			MethodName: "ChangeNoteContent",
			Handler:    _TodoService_ChangeNoteContent_Handler,
		},
		{
			MethodName: "MarkDoneById",
			Handler:    _TodoService_MarkDoneById_Handler,
		},
		{
			MethodName: "DelNoteById",
			Handler:    _TodoService_DelNoteById_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAllNotes",
			Handler:       _TodoService_GetAllNotes_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/protobuf/note.proto",
}
